# Generated by Django 5.2.4 on 2025-08-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonnement_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='abonnement_type',
            field=models.CharField(choices=[('basique', 'basique'), ('standard', 'Standard'), ('premium', 'Premium')], default='basique', max_length=50),
        ),
    ]
