# Generated by Django 5.2.4 on 2025-08-28 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_abonnement_debut_user_abonnement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonnement_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='type_de_user',
            field=models.CharField(choices=[('entreprise', 'Entreprise'), ('superadmin', 'Super Admin')], default='entreprise', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='abonnement_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='abonnement_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
