# Generated by Django 5.2.4 on 2025-08-30 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user_abonnement_fin_user_type_de_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='abonnement_fin',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
