# Generated by Django 5.2.4 on 2025-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_user_abonnement_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Basique', 'Basique'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=20, unique=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_jours', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
