# Generated by Django 5.2.4 on 2025-08-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='prix',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='prix_euros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
