# Generated by Django 5.2.4 on 2025-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_abonnement_prix_abonnement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Votre email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Écris une ligne par fonctionnalité (une ligne = un avantage)', null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='duree_jours',
            field=models.PositiveIntegerField(default=30, help_text="Durée de validité de l'abonnement en jours"),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='prix_euros',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Prix de l'abonnement en euros (€)", max_digits=6),
        ),
    ]
