# Generated by Django 5.2.4 on 2025-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_contactmessage_alter_abonnement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='nombre_cv',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de CV téléchargeables avec cet abonnement'),
        ),
    ]
