# Generated by Django 5.2.4 on 2025-08-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_abonnement_nombre_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre_cv_peut_telecharger',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
